server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置GitHub
          uri: https://github.com/matao-git/springcloud3.27.git
          #配置搜素目录
          search-paths:
          - configfiles
      #配置分支
      label: test
